[package]
name = "types"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { version = "0.29.0", features = ["serde", "bytemuck"] }
serde = { version = "1.0", features = ["derive"] }
bytemuck = { version = "1.16.1", features = ["derive"] }
redb = "2.6.0"
